//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadados de Relação EDM

[assembly: EdmRelationshipAttribute("XPTOModel", "FK_PRODUTO_USUARIO", "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XPTO.UserInfo.Core.USUARIO), "PRODUTO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XPTO.UserInfo.Core.PRODUTO), true)]

#endregion

namespace XPTO.UserInfo.Core
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class XPTOEntities : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto XPTOEntities usando a cadeia de conexão localizada na seção 'XPTOEntities' do arquivo de configuração do aplicativo.
        /// </summary>
        public XPTOEntities() : base("name=XPTOEntities", "XPTOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto XPTOEntities.
        /// </summary>
        public XPTOEntities(string connectionString) : base(connectionString, "XPTOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto XPTOEntities.
        /// </summary>
        public XPTOEntities(EntityConnection connection) : base(connection, "XPTOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<PRODUTO> PRODUTO
        {
            get
            {
                if ((_PRODUTO == null))
                {
                    _PRODUTO = base.CreateObjectSet<PRODUTO>("PRODUTO");
                }
                return _PRODUTO;
            }
        }
        private ObjectSet<PRODUTO> _PRODUTO;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<USUARIO> USUARIO
        {
            get
            {
                if ((_USUARIO == null))
                {
                    _USUARIO = base.CreateObjectSet<USUARIO>("USUARIO");
                }
                return _USUARIO;
            }
        }
        private ObjectSet<USUARIO> _USUARIO;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet PRODUTO. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToPRODUTO(PRODUTO pRODUTO)
        {
            base.AddObject("PRODUTO", pRODUTO);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet USUARIO. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToUSUARIO(USUARIO uSUARIO)
        {
            base.AddObject("USUARIO", uSUARIO);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XPTOModel", Name="PRODUTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRODUTO : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto PRODUTO.
        /// </summary>
        /// <param name="id">Valor inicial da propriedade id.</param>
        /// <param name="id_usuario">Valor inicial da propriedade id_usuario.</param>
        public static PRODUTO CreatePRODUTO(global::System.Int32 id, global::System.Int32 id_usuario)
        {
            PRODUTO pRODUTO = new PRODUTO();
            pRODUTO.id = id;
            pRODUTO.id_usuario = id_usuario;
            return pRODUTO;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value, "id_usuario");
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nm_produto
        {
            get
            {
                return _nm_produto;
            }
            set
            {
                Onnm_produtoChanging(value);
                ReportPropertyChanging("nm_produto");
                _nm_produto = StructuralObject.SetValidValue(value, true, "nm_produto");
                ReportPropertyChanged("nm_produto");
                Onnm_produtoChanged();
            }
        }
        private global::System.String _nm_produto;
        partial void Onnm_produtoChanging(global::System.String value);
        partial void Onnm_produtoChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XPTOModel", "FK_PRODUTO_USUARIO", "USUARIO")]
        public USUARIO USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("XPTOModel.FK_PRODUTO_USUARIO", "USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("XPTOModel.FK_PRODUTO_USUARIO", "USUARIO").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIO> USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("XPTOModel.FK_PRODUTO_USUARIO", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIO>("XPTOModel.FK_PRODUTO_USUARIO", "USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XPTOModel", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto USUARIO.
        /// </summary>
        /// <param name="id">Valor inicial da propriedade Id.</param>
        /// <param name="nome">Valor inicial da propriedade nome.</param>
        /// <param name="sobrenome">Valor inicial da propriedade sobrenome.</param>
        /// <param name="dt_nascimento">Valor inicial da propriedade dt_nascimento.</param>
        /// <param name="sexo">Valor inicial da propriedade sexo.</param>
        /// <param name="email">Valor inicial da propriedade email.</param>
        /// <param name="ativo">Valor inicial da propriedade ativo.</param>
        public static USUARIO CreateUSUARIO(global::System.Int32 id, global::System.String nome, global::System.String sobrenome, global::System.DateTime dt_nascimento, global::System.String sexo, global::System.String email, global::System.String ativo)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.Id = id;
            uSUARIO.nome = nome;
            uSUARIO.sobrenome = sobrenome;
            uSUARIO.dt_nascimento = dt_nascimento;
            uSUARIO.sexo = sexo;
            uSUARIO.email = email;
            uSUARIO.ativo = ativo;
            return uSUARIO;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sobrenome
        {
            get
            {
                return _sobrenome;
            }
            set
            {
                OnsobrenomeChanging(value);
                ReportPropertyChanging("sobrenome");
                _sobrenome = StructuralObject.SetValidValue(value, false, "sobrenome");
                ReportPropertyChanged("sobrenome");
                OnsobrenomeChanged();
            }
        }
        private global::System.String _sobrenome;
        partial void OnsobrenomeChanging(global::System.String value);
        partial void OnsobrenomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dt_nascimento
        {
            get
            {
                return _dt_nascimento;
            }
            set
            {
                Ondt_nascimentoChanging(value);
                ReportPropertyChanging("dt_nascimento");
                _dt_nascimento = StructuralObject.SetValidValue(value, "dt_nascimento");
                ReportPropertyChanged("dt_nascimento");
                Ondt_nascimentoChanged();
            }
        }
        private global::System.DateTime _dt_nascimento;
        partial void Ondt_nascimentoChanging(global::System.DateTime value);
        partial void Ondt_nascimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, false, "sexo");
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ativo
        {
            get
            {
                return _ativo;
            }
            set
            {
                OnativoChanging(value);
                ReportPropertyChanging("ativo");
                _ativo = StructuralObject.SetValidValue(value, false, "ativo");
                ReportPropertyChanged("ativo");
                OnativoChanged();
            }
        }
        private global::System.String _ativo;
        partial void OnativoChanging(global::System.String value);
        partial void OnativoChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XPTOModel", "FK_PRODUTO_USUARIO", "PRODUTO")]
        public EntityCollection<PRODUTO> PRODUTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PRODUTO>("XPTOModel.FK_PRODUTO_USUARIO", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PRODUTO>("XPTOModel.FK_PRODUTO_USUARIO", "PRODUTO", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
